import{a as g,S as R,i}from"./assets/vendor-CucEYOFD.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))a(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const n of r.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&a(n)}).observe(document,{childList:!0,subtree:!0});function o(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function a(e){if(e.ep)return;e.ep=!0;const r=o(e);fetch(e.href,r)}})();g.defaults.baseURL="https://pixabay.com/api/";async function p(s,t=1){const o="56406455-6dc399abae623877bee600229",a=new URLSearchParams({key:o,q:s,image_type:"photo",orientation:"horizontal",safesearch:"true",page:t,per_page:15});return(await g.get(`?${a}`)).data}const y=document.querySelector(".gallery"),d=document.querySelector(".loader"),u=document.querySelector(".load-more-btn"),$=new R(".gallery a",{captionsData:"alt",captionDelay:250});function b(s){const t=s.map(({webformatURL:o,largeImageURL:a,tags:e,likes:r,views:n,comments:P,downloads:q})=>`
      <li class="gallery-item">
        <a class="gallery-link" href="${a}">
          <img class="gallery-image" src="${o}" alt="${e}" />
        </a>
        <div class="info">
          <p class="info-item"><b>Likes</b> <br/> ${r}</p>
          <p class="info-item"><b>Views</b> <br/> ${n}</p>
          <p class="info-item"><b>Comments</b> <br/> ${P}</p>
          <p class="info-item"><b>Downloads</b> <br/> ${q}</p>
        </div>
      </li>
    `).join("");y.insertAdjacentHTML("beforeend",t),$.refresh()}function I(){y.innerHTML=""}function L(){d&&d.classList.remove("is-hidden")}function w(){d&&d.classList.add("is-hidden")}function S(){u&&u.classList.remove("is-hidden")}function f(){u&&u.classList.add("is-hidden")}const M=document.querySelector(".form"),h=document.querySelector(".load-more-btn");let c="",l=1,m=0;const v=15;M.addEventListener("submit",B);h&&h.addEventListener("click",E);async function B(s){s.preventDefault();const t=s.currentTarget;if(c=t.elements["search-text"].value.trim(),c===""){i.warning({title:"Warning",message:"Please enter a search term!",position:"topRight"});return}l=1,I(),f(),L();try{const o=await p(c,l);if(m=o.totalHits,o.hits.length===0){i.error({title:"Error",message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"});return}b(o.hits),m>v?S():i.info({title:"Info",message:"We're sorry, but you've reached the end of search results.",position:"topRight"})}catch(o){console.error(o),i.error({title:"Error",message:"Something went wrong. Please try again later.",position:"topRight"})}finally{w(),t.reset()}}async function E(){l+=1,f(),L();try{const s=await p(c,l);b(s.hits);const t=document.querySelector(".gallery-item");if(t){const{height:a}=t.getBoundingClientRect();window.scrollBy({top:a*2,behavior:"smooth"})}l*v>=m?(f(),i.info({title:"Info",message:"We're sorry, but you've reached the end of search results.",position:"topRight"})):S()}catch(s){console.error(s),i.error({title:"Error",message:"Failed to load more images!",position:"topRight"})}finally{w()}}
//# sourceMappingURL=index.js.map
