import{a as h,S as M,i as n}from"./assets/vendor-CucEYOFD.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))a(e);new MutationObserver(e=>{for(const o of e)if(o.type==="childList")for(const s of o.addedNodes)s.tagName==="LINK"&&s.rel==="modulepreload"&&a(s)}).observe(document,{childList:!0,subtree:!0});function r(e){const o={};return e.integrity&&(o.integrity=e.integrity),e.referrerPolicy&&(o.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?o.credentials="include":e.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function a(e){if(e.ep)return;e.ep=!0;const o=r(e);fetch(e.href,o)}})();h.defaults.baseURL="https://pixabay.com/api/";async function g(i,t=1){const r="56406455-6dc399abae623877bee600229",a=new URLSearchParams({key:r,q:i,image_type:"photo",orientation:"horizontal",safesearch:"true",page:t,per_page:15});return(await h.get(`?${a}`)).data}const p=document.querySelector(".gallery"),d=document.querySelector(".loader"),u=document.querySelector(".load-more-btn"),$=new M(".gallery a",{captionsData:"alt",captionDelay:250});function y(i){const t=i.map(({webformatURL:r,largeImageURL:a,tags:e,likes:o,views:s,comments:v,downloads:q})=>`
      <li class="gallery-item">
        <a class="gallery-link" href="${a}">
          <img class="gallery-image" src="${r}" alt="${e}" />
        </a>
        <div class="info">
          <p class="info-item"><b>Likes</b> <br/> ${o}</p>
          <p class="info-item"><b>Views</b> <br/> ${s}</p>
          <p class="info-item"><b>Comments</b> <br/> ${v}</p>
          <p class="info-item"><b>Downloads</b> <br/> ${q}</p>
        </div>
      </li>
    `).join("");p.insertAdjacentHTML("beforeend",t),$.refresh()}function R(){p.innerHTML=""}function b(){d&&d.classList.remove("is-hidden")}function L(){d&&d.classList.add("is-hidden")}function w(){u&&u.classList.remove("is-hidden")}function S(){u&&u.classList.add("is-hidden")}const B=document.querySelector(".form"),m=document.querySelector(".load-more-btn");let l="",c=1,f=0;const P=15;B.addEventListener("submit",E);m&&m.addEventListener("click",O);async function E(i){i.preventDefault();const t=i.currentTarget;if(l=t.elements["search-text"].value.trim(),l===""){n.warning({title:"Warning",message:"Please enter a search term!",position:"topRight"});return}c=1,R(),S(),b();try{const r=await g(l,c);if(f=r.totalHits,r.hits.length===0){n.error({title:"Error",message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"});return}y(r.hits),f>P&&w()}catch(r){console.error(r),n.error({title:"Error",message:"Something went wrong. Please try again later.",position:"topRight"})}finally{L(),t.reset()}}async function O(){c+=1,S(),b();try{const i=await g(l,c);y(i.hits);const t=document.querySelector(".gallery-item");if(t){const{height:a}=t.getBoundingClientRect();window.scrollBy({top:a*2,behavior:"smooth"})}const r=Math.ceil(f/P);c>=r?n.info({title:"Info",message:"We're sorry, but you've reached the end of search results.",position:"topRight"}):w()}catch(i){console.error(i),n.error({title:"Error",message:"Failed to load more images!",position:"topRight"})}finally{L()}}
//# sourceMappingURL=index.js.map
